ARG NODE_VERSION=alpine
ARG NGINX_VERSION=alpine

FROM node:${NODE_VERSION} AS build
RUN adduser -D -h /project build
USER build
WORKDIR /project
COPY --chown=build:build . /project
RUN npm install
RUN npm run build

FROM nginx:${NGINX_VERSION}
COPY --from=build --chown=nginx:nginx /project/build /usr/share/nginx/html
